include themes/noctalia.conf

font_family      JetBrainsMono Nerd Font
font_size        12

# --- плавный «шлейф» курсора (тот самый эффект) ---
cursor_trail            3
cursor_trail_decay      0.1 0.4
cursor_shape            beam

# косметика
window_padding_width    8
background_opacity       0.92
confirm_os_window_close  0

# fish как шелл именно в kitty (см. пункт 5)
shell /usr/bin/fish
